
services:
  # PostgreSQL Database
  db:
    image: postgres:17-alpine
    container_name: flask-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Soumya1997
      POSTGRES_DB: Flask_App2
    ports:
      - "5433:5432"  # Host 5433 -> container 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: flask-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Flask Backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/myapp
      - /myapp/venv              
      - /myapp/__pycache__ 
    env_file:
      - ./Backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:Soumya1997@db:5432/Flask_App2
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Vite Frontend
  frontend:
    build:
      context: ./fontend
      dockerfile: Dockerfile
    # image: ismsoft-frontend:latest
    container_name: ismsoft-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./fontend:/mywebapp
      - /mywebapp/node_modules
    # environment:
    #   VITE_BACKEND_URL: http://127.0.0.1:5000/api/v1
    depends_on:
      - backend
    restart: unless-stopped

# Named volumes
volumes:
  postgres_data:
  redis_data:

# Custom network
networks:
  default:
    name: ismsoft-network
