"""Initial migration

Revision ID: c3c4d4f021cb
Revises: f237a2392de7
Create Date: 2025-06-24 19:09:42.743384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c4d4f021cb'
down_revision = 'f237a2392de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('clients_org_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint('clients_org_email_key', ['org_email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
